FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Eksponiramo Vite port
EXPOSE 5173

# Vite zahteva --host flag da bi bio dostupan izvan kontejnera
CMD ["npm", "run", "dev", "--", "--host"]